services:
  mattermost:
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./eval:/app/eval

  web:
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./eval:/app/eval
